#!/bin/bash

# set up urlwatch to restart chromium when config changes
echo http://info.api.no/etc/walldisplay/$(cat /sys/class/net/eth0/address) > /home/pi/.urlwatch/urls.txt
echo "* * * * * urlwatch | grep ^CHANGED && killall chromium" | crontab

while true; do

	# Clean up previously running apps, gracefully at first then harshly
	killall -TERM chromium 2>/dev/null;
	killall -TERM matchbox-window-manager 2>/dev/null;
	sleep 2;
	killall -9 chromium 2>/dev/null;
	killall -9 matchbox-window-manager 2>/dev/null;

	# Clean out existing profile information
	rm -rf /home/pi/.cache;
	rm -rf /home/pi/.config;
	rm -rf /home/pi/.pki;

	# Generate the bare minimum to keep Chromium happy!
	mkdir -p /home/pi/.config/chromium/Default
	sqlite3 /home/pi/.config/chromium/Default/Web\ Data "CREATE TABLE meta(key LONGVARCHAR NOT NULL UNIQUE PRIMARY KEY, value LONGVARCHAR); INSERT INTO meta VALUES('version','46'); CREATE TABLE keywords (foo INTEGER);";

	# Disable DPMS / Screen blanking
	xset -dpms
	xset s off

	# Reset the framebuffer's colour-depth
	fbset -depth $( cat /sys/module/*fb*/parameters/fbdepth );

	# Hide the cursor (move it to the bottom-right, comment out if you want mouse interaction)
	xwit -root -warp $( cat /sys/module/*fb*/parameters/fbwidth ) $( cat /sys/module/*fb*/parameters/fbheight )

	# Start the window manager (remove "-use_cursor no" if you actually want mouse interaction)
	matchbox-window-manager -use_titlebar no -use_cursor no &

        URL=file:///tmp/info.html
        MAC=$(cat /sys/class/net/eth0/address)
        IP=$(hostname -I)

cat >/tmp/info.html <<_EOT_
<html>
<body>
<p>HW Address: $MAC</p>
<p>IP Address: $IP</p>
</body>
</html>
_EOT_

curl -o /tmp/config http://info.api.no/etc/walldisplay/$MAC
grep URL /tmp/config || echo "URL=file:///tmp/info.html" > /tmp/config
. /tmp/config

	# Start the browser (See http://peter.sh/experiments/chromium-command-line-switches/)
	chromium --disable-translate --app="$URL"

done;

