#! /bin/sh
### BEGIN INIT INFO
# Provides:          walldisplay-sethostname
# Required-Start:
# Required-Stop:
# Should-Start:      
# Default-Start:     S 2
# Default-Stop:
# Short-Description: Edits /etc/hostname, setting it to something unique
# Description:       Walldisplay specific hostname
### END INIT INFO

PATH=/sbin:/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start () {
        hostname walldisplay-$(cat /sys/class/net/eth0/address | sed s'/:/-/g')
	exit 0
}

do_status () {
	HOSTNAME=$(hostname)
	if [ "$HOSTNAME" ] ; then
		return 0
	else
		return 4
	fi
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# No-op
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: hostname.sh [start|stop]" >&2
	exit 3
	;;
esac

:
